alias :w='passiveAggressiveVim.sh'
alias :q='passiveAggressiveVim.sh'
alias :q!='passiveAggressiveVim.sh'
alias :wq='passiveAggressiveVim.sh'
alias :x='passiveAggressiveVim.sh'
alias :x!='passiveAggressiveVim.sh'
